name: google-cloud-datastore-odm-test
services:
  datastore:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    ports:
      - "20001:8081"
    command: >
      gcloud beta emulators datastore start
      --project=google-cloud-datastore-odm-test
      --host-port=0.0.0.0:8081
      --consistency=1.0
      --no-store-on-disk
