name: google-cloud-datastore-odm
services:
  datastore-dev:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    ports:
      - "10000:8081"
    volumes:
      - datastore-dev:/datastore
    command: >
      gcloud emulators firestore start
      --database-mode=datastore-mode
      --project=google-cloud-datastore-odm-dev
      --host-port=0.0.0.0:8081

  datastore-test:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    ports:
      - "10001:8081"
    command: >
      gcloud emulators firestore start
      --database-mode=datastore-mode
      --project=google-cloud-datastore-odm-test
      --host-port=0.0.0.0:8081

  emulators-ui:
    image: ghcr.io/drehelis/gcp-emulator-ui:main
    ports:
      - "10002:80"
    depends_on:
      - datastore-dev
    environment:
      DATASTORE_EMULATOR_URL: datastore-dev:8081
      # fill the rest with dummies as runtime needs them
      STORAGE_EMULATOR_URL: host.docker.internal
      PUBSUB_EMULATOR_URL: host.docker.internal
      FIRESTORE_EMULATOR_URL: host.docker.internal
      DATASTORE_FILE_SERVER_URL: host.docker.internal

volumes:
  datastore-dev:
